# Site Settings
title: Jon  CV
url: 'https://fif0o.github.io' #jonathanlazarini.com
baseurl: '/online-cv' #change it according to your repository name

#Profile information
name: Jon Lazarini
tagline: UX Engineer
pic: jonlazarini.png
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.
Heading of front-end teams for several years, expanding today to a wider set of technologies.

Functional Programming, Haskell, Elm, IoT and Ops are my new hobbyhorses.'

#sidebar links
email: jonathan.lazarini@wanadoo.fr
phone: +447 446 130 391
website: fif0o.github.io #do not add http://
linkedin: jonathanlazarini
github: fif0o
twitter: '@fif0o'

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

exclude:
  - Guardfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - package.json
  - assets/less
  - node_modules
  - gulpfile.js
  - .history