# Site Settings
title: Jon  CV
url: 'https://fif0o.github.io' #jonathanlazarini.com
baseurl: '/online-cv' #change it according to your repository name

#Profile information
name: Alan Doe
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: hello@webjeda.com
phone: 012 345 6789
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

exclude:
  - Guardfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - package.json
  - assets/less
  - node_modules
  - gulpfile.js
  - .history