# Site Settings
title: Jon  CV
url: 'https://fif0o.github.io' #jonathanlazarini.com
baseurl: '/online-cv' #change it according to your repository name - http://127.0.0.1:4000/online-cv/

#Profile information
name: Jon Lazarini
tagline: UX Practioner & Front-End Engineer
pic: jonlazarini.png
summary: 'I am a UX Practioner & Front-End Engineer with over 10 years of experience combining Service design, User Centric approaches with a big interest for Front-end development.
</br></br>
I worked across sectors (Finance, Oil & Gas, Automotive, HR, NGO, Defense, Teleco, Retail, Fashion) delivering products on various platforms (web, native).
My experiences include helping stakeholders define products, giving a voice to customers, and iterating with rapid protoyping solutions. I also have an interest in crafting design systems for organisations when needed.
You can have a look at some of the public projects on this <a href="https://fif0o.github.io" target="_blank">website</a>.
</br></br>
I am a huge advocate of agile, lean frameworks.
My new aspirations are still trying to create user centered solutions and learning more about machine learning, deep learning, artificial intelligence, neural networks & electronics.'

#sidebar links
email: jonathan.lazarini@wanadoo.fr
phone: +447446130391
website: fif0o.github.io #do not add http://
linkedin: jonathanlazarini
github: fif0o
twitter: '@fif0o'

# Tracker
analytics: UA-77360167-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

exclude:
  - Guardfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - package.json
  - assets/less
  - node_modules
  - gulpfile.js
  - .history